#!/usr/bin/env sh
set -e

usage() {
  echo "Usage: $0 [-r repository_link] [-D/A] key [file/stdin]" 
  echo "  -r repository_link : Git repository to use (default: \$GIT_KV_REPO)" 
  echo "  -D                 : Delete the specified key from the kv store" 
  echo "  -A                 : Append to the specified key in the kv store" 
  echo "  key                : The key to update in the kv store" 
  echo "  file/stdin         : File containing the data to store, or '-' for stdin" 
}

action="S" # Default action is set

while getopts "r:DAh" opt; do
  case $opt in
    r)
      GIT_KV_REPO="$OPTARG"
      ;;
    D|A)
      action="$opt"
      ;;
    h)
      usage
      exit 0
      ;;
    *)
      usage
      exit 1
      ;;
  esac
done
shift $((OPTIND -1))

key="$1"
file="$2"
[ -z "$key" ] && usage && exit 1
[ -z "$GIT_KV_REPO" ] && echo "No target git repository set" >/dev/stderr && exit 1

if [ "$action" != "D" ]; then
  if [ -z "$file" ] || [ "$file" = "-" ]; then
    input_data=$(cat)
  else
    input_data=$(cat "$file")
  fi
fi

tmp_dir=$(mktemp -d)
git clone --depth 1 "$GIT_KV_REPO" "$tmp_dir" 2>/dev/stderr || {
  echo "Failed to clone repository $GIT_KV_REPO" >/dev/stderr
  rm -rf "$tmp_dir"
  exit 1
}

# Commit the input data to the git repository.
cd "$tmp_dir"

case "$action" in
  D) git rm -f "$key" 2>/dev/null || true ;;
  A) echo "$input_data" >> "$key" ;;
  S) echo "$input_data" > "$key" ;;
esac

echo "Updating $key in $GIT_KV_REPO" >/dev/stderr
{
git add .
git commit -m "$(date)"
git remote set-url origin "$GIT_KV_REPO"
git push -f origin HEAD:main
} 2>/dev/stderr
echo "Updated $key in $GIT_KV_REPO" >/dev/stderr

branch=$(git branch --show-current 2>/dev/null || echo "main")

# Output the raw content url that is fetchable via curl/wget
rawify_url() {
  case $1 in
    *github.com*)
      echo "$1" | tr ':' '/' | sed -e 's/git@/https:\/\//' | sed -e 's/github.com/raw.githubusercontent.com/' -e 's/\/blob\//\//' | sed -e 's/$/\/refs\/heads\/'"$branch\/$key"'/'
      ;;
    *)
      echo "Unsupported git host for raw content URL generation." >&2
      exit 1
      ;;
  esac
}

repo_url=$(echo "$GIT_KV_REPO" | sed -e 's/\.git$//')
raw_url=$(rawify_url "$repo_url")
echo "$raw_url"

# Cleanup
rm -rf "$tmp_dir"
